# Generated by Django 3.1b1 on 2020-11-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
