# Generated by Django 3.1b1 on 2020-11-01 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 11, 1, 17, 6, 24, 593505, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
    ]
