# Generated by Django 3.1b1 on 2020-11-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201101_1947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
